= Guestbook Luminus
:numbered:
:toc:

== Introduction

The software in this repository was build using the book
"Web Development with Clojure" 3rd edition written by
Dmitri Sotnikov and Scot Brown.

== Prerequisites

Please make sure that you have Leiningen, Clojure and Babashka available.
Babashka was introduced to make building (setting up node and installing js stuff easier).

----
$ lein -version
Leiningen 2.9.10 on Java 17.0.5 OpenJDK 64-Bit Server VM

$ clj --version
Clojure CLI version 1.11.1.1105

$ bb --version
babashka v0.9.162
----

== Versions used to build this

Generated with Leiningen. See output below

----
include::new-output.txt[]
----

== Running

To start a web server for the application, run:

    # From the command-line, install node
    bb node-install
    # From the command-line, install JavaScript packages
    bb npm-install
    # From the command-line (or from your IDE), run a repl
    lein repl
    # In the repl, when running this for the first time, initialize the database
    (migrate)
    # Start the back-end from the repl
    (start)
    # From the command-line, run frontend
    lein cljsbuild auto

== License

See LICENCE